### ISSUE TITLE
Please update elm-community/list-extra

### ISSUE THREAD

**Issue by razzeee** [waratuman/elm-coder#2]
I'm trying to use this library via elm-jsonwebtoken
https://github.com/ktonon/elm-jsonwebtoken/blob/1.0.2/elm-package.json

But it clashes with another of my dependencies, that is already using a newer version of `elm-community/list-extra`. Causing me to not be able to install anything.

**Comment by waratuman** [comment]
Finally resolved, sorry for the long delay.
