### ISSUE TITLE
Drop Result from return type for encode functions

### ISSUE THREAD

**Issue by Malax** [waratuman/elm-coder#3]
All currently implemented schemes (base16, base32 and base64) [are defined](https://tools.ietf.org/html/rfc4648) for arbitrary sequences of bytes and encoding should never fail. In contrast, all `encode` functions currently return a `Result String String` which makes working with this package more clunky than necessary.

From my understanding, the `Result` type is used internally in an abstraction (`intToChar`) that allows to generically implement different `Scheme`s using common core code.

I understand that there is some unsafety involved since there is no `Byte` type that can ensure users only call `encode` with a list of valid bytes (integers from `0x00` to `0xFF`). 

There is some precedent in other packages (https://github.com/rtfeldman/elm-hex/blob/master/src/Hex.elm#L138) that provide functions prefixed with `unsafe` that require users to pass in only valid values in cases where Elm's type-system cannot enforce them. This allows a more pragmatic API.

Would it be possible to re-implement the public API so that `encode`-type functions do not return a `Result String String`? This might be an issue when this package supports more `Scheme`s in the future that can fail while encoding.

I'd be happy to discuss this further! :)

**Comment by waratuman** [comment]
Yes, I'll look into this a little more. Seems reasonable to me, at the time I think I was even debating if I needed the `Result`. But if the Hex library has set the precedent, I see no reason not to.

Sorry for the delayed response.

**Comment by waratuman** [comment]
I've opened a PR with a potential solution. https://github.com/waratuman/elm-coder/pull/4
